// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: prototypes.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Arg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref uint32 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Dir uint32 `protobuf:"varint,2,opt,name=dir,proto3" json:"dir,omitempty"` // there is no uint8
	// Types that are assignable to Subtype:
	//	*Arg_PtrArg
	//	*Arg_GroupArg_
	//	*Arg_ConstArg_
	//	*Arg_UnionArg_
	//	*Arg_ResArg
	//	*Arg_DataArg_
	Subtype isArg_Subtype `protobuf_oneof:"subtype"`
}

func (x *Arg) Reset() {
	*x = Arg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0}
}

func (x *Arg) GetRef() uint32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *Arg) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (m *Arg) GetSubtype() isArg_Subtype {
	if m != nil {
		return m.Subtype
	}
	return nil
}

func (x *Arg) GetPtrArg() *Arg_PointerArg {
	if x, ok := x.GetSubtype().(*Arg_PtrArg); ok {
		return x.PtrArg
	}
	return nil
}

func (x *Arg) GetGroupArg() *Arg_GroupArg {
	if x, ok := x.GetSubtype().(*Arg_GroupArg_); ok {
		return x.GroupArg
	}
	return nil
}

func (x *Arg) GetConstArg() *Arg_ConstArg {
	if x, ok := x.GetSubtype().(*Arg_ConstArg_); ok {
		return x.ConstArg
	}
	return nil
}

func (x *Arg) GetUnionArg() *Arg_UnionArg {
	if x, ok := x.GetSubtype().(*Arg_UnionArg_); ok {
		return x.UnionArg
	}
	return nil
}

func (x *Arg) GetResArg() *Arg_ResultArg {
	if x, ok := x.GetSubtype().(*Arg_ResArg); ok {
		return x.ResArg
	}
	return nil
}

func (x *Arg) GetDataArg() *Arg_DataArg {
	if x, ok := x.GetSubtype().(*Arg_DataArg_); ok {
		return x.DataArg
	}
	return nil
}

type isArg_Subtype interface {
	isArg_Subtype()
}

type Arg_PtrArg struct {
	PtrArg *Arg_PointerArg `protobuf:"bytes,3,opt,name=ptr_arg,json=ptrArg,proto3,oneof"`
}

type Arg_GroupArg_ struct {
	GroupArg *Arg_GroupArg `protobuf:"bytes,4,opt,name=group_arg,json=groupArg,proto3,oneof"`
}

type Arg_ConstArg_ struct {
	ConstArg *Arg_ConstArg `protobuf:"bytes,5,opt,name=const_arg,json=constArg,proto3,oneof"`
}

type Arg_UnionArg_ struct {
	UnionArg *Arg_UnionArg `protobuf:"bytes,6,opt,name=union_arg,json=unionArg,proto3,oneof"`
}

type Arg_ResArg struct {
	ResArg *Arg_ResultArg `protobuf:"bytes,7,opt,name=res_arg,json=resArg,proto3,oneof"`
}

type Arg_DataArg_ struct {
	DataArg *Arg_DataArg `protobuf:"bytes,8,opt,name=data_arg,json=dataArg,proto3,oneof"`
}

func (*Arg_PtrArg) isArg_Subtype() {}

func (*Arg_GroupArg_) isArg_Subtype() {}

func (*Arg_ConstArg_) isArg_Subtype() {}

func (*Arg_UnionArg_) isArg_Subtype() {}

func (*Arg_ResArg) isArg_Subtype() {}

func (*Arg_DataArg_) isArg_Subtype() {}

type EvtrackEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId   uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType uint32 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Ptr       uint64 `protobuf:"varint,3,opt,name=ptr,proto3" json:"ptr,omitempty"`
	Size      uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	NumTrace  uint32 `protobuf:"varint,5,opt,name=num_trace,json=numTrace,proto3" json:"num_trace,omitempty"`
	// TimeStamp is not used
	// ObjId is not used
	// InstrId is not used
	Trace   []uint32 `protobuf:"varint,6,rep,packed,name=trace,proto3" json:"trace,omitempty"`
	Syscall string   `protobuf:"bytes,7,opt,name=syscall,proto3" json:"syscall,omitempty"`
	Args    []*Arg   `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *EvtrackEvent) Reset() {
	*x = EvtrackEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvtrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvtrackEvent) ProtoMessage() {}

func (x *EvtrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvtrackEvent.ProtoReflect.Descriptor instead.
func (*EvtrackEvent) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{1}
}

func (x *EvtrackEvent) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EvtrackEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *EvtrackEvent) GetPtr() uint64 {
	if x != nil {
		return x.Ptr
	}
	return 0
}

func (x *EvtrackEvent) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EvtrackEvent) GetNumTrace() uint32 {
	if x != nil {
		return x.NumTrace
	}
	return 0
}

func (x *EvtrackEvent) GetTrace() []uint32 {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *EvtrackEvent) GetSyscall() string {
	if x != nil {
		return x.Syscall
	}
	return ""
}

func (x *EvtrackEvent) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

type EventsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*EvtrackEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *EventsList) Reset() {
	*x = EventsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsList) ProtoMessage() {}

func (x *EventsList) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsList.ProtoReflect.Descriptor instead.
func (*EventsList) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{2}
}

func (x *EventsList) GetEvents() []*EvtrackEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// size is only required for efficiency inside the vm
	Evts []*EventsList `protobuf:"bytes,1,rep,name=evts,proto3" json:"evts,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{3}
}

func (x *Batch) GetEvts() []*EventsList {
	if x != nil {
		return x.Evts
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NumGroups uint32        `protobuf:"varint,2,opt,name=num_groups,json=numGroups,proto3" json:"num_groups,omitempty"`
	Events    []*EventsList `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{4}
}

func (x *Group) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetNumGroups() uint32 {
	if x != nil {
		return x.NumGroups
	}
	return 0
}

func (x *Group) GetEvents() []*EventsList {
	if x != nil {
		return x.Events
	}
	return nil
}

type ChangedGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ChangedGroups) Reset() {
	*x = ChangedGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangedGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedGroups) ProtoMessage() {}

func (x *ChangedGroups) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedGroups.ProtoReflect.Descriptor instead.
func (*ChangedGroups) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{5}
}

func (x *ChangedGroups) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type DeletedGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted []uint64 `protobuf:"varint,1,rep,packed,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeletedGroups) Reset() {
	*x = DeletedGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletedGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedGroups) ProtoMessage() {}

func (x *DeletedGroups) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedGroups.ProtoReflect.Descriptor instead.
func (*DeletedGroups) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{6}
}

func (x *DeletedGroups) GetDeleted() []uint64 {
	if x != nil {
		return x.Deleted
	}
	return nil
}

type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Syscalls []string `protobuf:"bytes,1,rep,name=syscalls,proto3" json:"syscalls,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{7}
}

func (x *Program) GetSyscalls() []string {
	if x != nil {
		return x.Syscalls
	}
	return nil
}

type Programs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progs []*Program `protobuf:"bytes,1,rep,name=progs,proto3" json:"progs,omitempty"`
}

func (x *Programs) Reset() {
	*x = Programs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Programs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Programs) ProtoMessage() {}

func (x *Programs) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Programs.ProtoReflect.Descriptor instead.
func (*Programs) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{8}
}

func (x *Programs) GetProgs() []*Program {
	if x != nil {
		return x.Progs
	}
	return nil
}

type Arg_PointerArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint64 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	VmaSize uint64 `protobuf:"varint,2,opt,name=vma_size,json=vmaSize,proto3" json:"vma_size,omitempty"`
	Res     *Arg   `protobuf:"bytes,3,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *Arg_PointerArg) Reset() {
	*x = Arg_PointerArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_PointerArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_PointerArg) ProtoMessage() {}

func (x *Arg_PointerArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_PointerArg.ProtoReflect.Descriptor instead.
func (*Arg_PointerArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Arg_PointerArg) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Arg_PointerArg) GetVmaSize() uint64 {
	if x != nil {
		return x.VmaSize
	}
	return 0
}

func (x *Arg_PointerArg) GetRes() *Arg {
	if x != nil {
		return x.Res
	}
	return nil
}

type Arg_GroupArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inner []*Arg `protobuf:"bytes,1,rep,name=inner,proto3" json:"inner,omitempty"`
}

func (x *Arg_GroupArg) Reset() {
	*x = Arg_GroupArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_GroupArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_GroupArg) ProtoMessage() {}

func (x *Arg_GroupArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_GroupArg.ProtoReflect.Descriptor instead.
func (*Arg_GroupArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Arg_GroupArg) GetInner() []*Arg {
	if x != nil {
		return x.Inner
	}
	return nil
}

type Arg_ConstArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val uint64 `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Arg_ConstArg) Reset() {
	*x = Arg_ConstArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_ConstArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_ConstArg) ProtoMessage() {}

func (x *Arg_ConstArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_ConstArg.ProtoReflect.Descriptor instead.
func (*Arg_ConstArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Arg_ConstArg) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Arg_UnionArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArgOption *Arg  `protobuf:"bytes,1,opt,name=arg_option,json=argOption,proto3" json:"arg_option,omitempty"` // option is a keyword in protobuf
	Index     int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *Arg_UnionArg) Reset() {
	*x = Arg_UnionArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_UnionArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_UnionArg) ProtoMessage() {}

func (x *Arg_UnionArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_UnionArg.ProtoReflect.Descriptor instead.
func (*Arg_UnionArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Arg_UnionArg) GetArgOption() *Arg {
	if x != nil {
		return x.ArgOption
	}
	return nil
}

func (x *Arg_UnionArg) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Our generation mechanism doesn't use recorded result args. Should we just
// ignore this and save us from the pain?
type Arg_ResultArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res   *Arg_ResultArg `protobuf:"bytes,1,opt,name=res,proto3,oneof" json:"res,omitempty"`
	OpDiv uint64         `protobuf:"varint,2,opt,name=op_div,json=opDiv,proto3" json:"op_div,omitempty"`
	OpAdd uint64         `protobuf:"varint,3,opt,name=op_add,json=opAdd,proto3" json:"op_add,omitempty"`
	Val   uint64         `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Arg_ResultArg) Reset() {
	*x = Arg_ResultArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_ResultArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_ResultArg) ProtoMessage() {}

func (x *Arg_ResultArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_ResultArg.ProtoReflect.Descriptor instead.
func (*Arg_ResultArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Arg_ResultArg) GetRes() *Arg_ResultArg {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *Arg_ResultArg) GetOpDiv() uint64 {
	if x != nil {
		return x.OpDiv
	}
	return 0
}

func (x *Arg_ResultArg) GetOpAdd() uint64 {
	if x != nil {
		return x.OpAdd
	}
	return 0
}

func (x *Arg_ResultArg) GetVal() uint64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Arg_DataArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Arg_DataArg) Reset() {
	*x = Arg_DataArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototypes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arg_DataArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg_DataArg) ProtoMessage() {}

func (x *Arg_DataArg) ProtoReflect() protoreflect.Message {
	mi := &file_prototypes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg_DataArg.ProtoReflect.Descriptor instead.
func (*Arg_DataArg) Descriptor() ([]byte, []int) {
	return file_prototypes_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Arg_DataArg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Arg_DataArg) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_prototypes_proto protoreflect.FileDescriptor

var file_prototypes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x22, 0xb2, 0x06, 0x0a,
	0x03, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x74, 0x72, 0x5f,
	0x61, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b,
	0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x06, 0x70, 0x74, 0x72, 0x41, 0x72, 0x67, 0x12, 0x35, 0x0a,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x41, 0x72, 0x67, 0x12, 0x35, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x5f, 0x61, 0x72,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75,
	0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x41, 0x72, 0x67, 0x48,
	0x00, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x41, 0x72, 0x67, 0x12, 0x35, 0x0a, 0x09, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x41,
	0x72, 0x67, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x72, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41,
	0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x67, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x41, 0x72, 0x67, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x61,
	0x72, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66,
	0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x67, 0x48,
	0x00, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x41, 0x72, 0x67, 0x1a, 0x62, 0x0a, 0x0a, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6d, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x6d, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x6f, 0x6f,
	0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x52, 0x03, 0x72, 0x65, 0x73, 0x1a, 0x2f,
	0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b,
	0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a,
	0x1c, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x1a, 0x4e, 0x0a,
	0x08, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x12, 0x2c, 0x0a, 0x0a, 0x61, 0x72, 0x67,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x52, 0x09, 0x61, 0x72,
	0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x83, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x67, 0x12, 0x2e, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66,
	0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x72,
	0x67, 0x48, 0x00, 0x52, 0x03, 0x72, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x70, 0x5f, 0x64, 0x69, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x70, 0x44,
	0x69, 0x76, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x72, 0x65, 0x73, 0x1a, 0x31, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70,
	0x65, 0x22, 0xde, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x74, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x12,
	0x21, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0x3c, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x45, 0x76, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x31, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x04, 0x65, 0x76, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75,
	0x7a, 0x7a, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x65,
	0x76, 0x74, 0x73, 0x22, 0x64, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x75, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x6e, 0x75, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x6f,
	0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x0d, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x6f, 0x6f,
	0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x25,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x79, 0x73,
	0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x79, 0x73,
	0x63, 0x61, 0x6c, 0x6c, 0x73, 0x22, 0x33, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6f, 0x6f, 0x6f, 0x6b, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x67, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x65, 0x76,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prototypes_proto_rawDescOnce sync.Once
	file_prototypes_proto_rawDescData = file_prototypes_proto_rawDesc
)

func file_prototypes_proto_rawDescGZIP() []byte {
	file_prototypes_proto_rawDescOnce.Do(func() {
		file_prototypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_prototypes_proto_rawDescData)
	})
	return file_prototypes_proto_rawDescData
}

var file_prototypes_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_prototypes_proto_goTypes = []interface{}{
	(*Arg)(nil),            // 0: oookfuzz.Arg
	(*EvtrackEvent)(nil),   // 1: oookfuzz.EvtrackEvent
	(*EventsList)(nil),     // 2: oookfuzz.EventsList
	(*Batch)(nil),          // 3: oookfuzz.Batch
	(*Group)(nil),          // 4: oookfuzz.Group
	(*ChangedGroups)(nil),  // 5: oookfuzz.ChangedGroups
	(*DeletedGroups)(nil),  // 6: oookfuzz.DeletedGroups
	(*Program)(nil),        // 7: oookfuzz.Program
	(*Programs)(nil),       // 8: oookfuzz.Programs
	(*Arg_PointerArg)(nil), // 9: oookfuzz.Arg.PointerArg
	(*Arg_GroupArg)(nil),   // 10: oookfuzz.Arg.GroupArg
	(*Arg_ConstArg)(nil),   // 11: oookfuzz.Arg.ConstArg
	(*Arg_UnionArg)(nil),   // 12: oookfuzz.Arg.UnionArg
	(*Arg_ResultArg)(nil),  // 13: oookfuzz.Arg.ResultArg
	(*Arg_DataArg)(nil),    // 14: oookfuzz.Arg.DataArg
}
var file_prototypes_proto_depIdxs = []int32{
	9,  // 0: oookfuzz.Arg.ptr_arg:type_name -> oookfuzz.Arg.PointerArg
	10, // 1: oookfuzz.Arg.group_arg:type_name -> oookfuzz.Arg.GroupArg
	11, // 2: oookfuzz.Arg.const_arg:type_name -> oookfuzz.Arg.ConstArg
	12, // 3: oookfuzz.Arg.union_arg:type_name -> oookfuzz.Arg.UnionArg
	13, // 4: oookfuzz.Arg.res_arg:type_name -> oookfuzz.Arg.ResultArg
	14, // 5: oookfuzz.Arg.data_arg:type_name -> oookfuzz.Arg.DataArg
	0,  // 6: oookfuzz.EvtrackEvent.args:type_name -> oookfuzz.Arg
	1,  // 7: oookfuzz.EventsList.events:type_name -> oookfuzz.EvtrackEvent
	2,  // 8: oookfuzz.Batch.evts:type_name -> oookfuzz.EventsList
	2,  // 9: oookfuzz.Group.events:type_name -> oookfuzz.EventsList
	4,  // 10: oookfuzz.ChangedGroups.groups:type_name -> oookfuzz.Group
	7,  // 11: oookfuzz.Programs.progs:type_name -> oookfuzz.Program
	0,  // 12: oookfuzz.Arg.PointerArg.res:type_name -> oookfuzz.Arg
	0,  // 13: oookfuzz.Arg.GroupArg.inner:type_name -> oookfuzz.Arg
	0,  // 14: oookfuzz.Arg.UnionArg.arg_option:type_name -> oookfuzz.Arg
	13, // 15: oookfuzz.Arg.ResultArg.res:type_name -> oookfuzz.Arg.ResultArg
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_prototypes_proto_init() }
func file_prototypes_proto_init() {
	if File_prototypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prototypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvtrackEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangedGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletedGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Programs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_PointerArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_GroupArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_ConstArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_UnionArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_ResultArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototypes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arg_DataArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_prototypes_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Arg_PtrArg)(nil),
		(*Arg_GroupArg_)(nil),
		(*Arg_ConstArg_)(nil),
		(*Arg_UnionArg_)(nil),
		(*Arg_ResArg)(nil),
		(*Arg_DataArg_)(nil),
	}
	file_prototypes_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prototypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prototypes_proto_goTypes,
		DependencyIndexes: file_prototypes_proto_depIdxs,
		MessageInfos:      file_prototypes_proto_msgTypes,
	}.Build()
	File_prototypes_proto = out.File
	file_prototypes_proto_rawDesc = nil
	file_prototypes_proto_goTypes = nil
	file_prototypes_proto_depIdxs = nil
}

